[workspace]
members = ["eyelvl"]
exclude = ["tool/antlr4-rust-target/runtime/Rust"]

[package]
name = "libsl"
version = "0.1.0"
edition = "2024"

[dependencies]
antlr-rust = { path = "tool/antlr4-rust-target/runtime/Rust" }
