[package]
name = "eyelvl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
color-eyre = "0.6.3"
libsl = { path = ".." }
antlr-rust = { path = "../tool/antlr4-rust-target/runtime/Rust" }
