[package]
name = "eyelvl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
color-eyre = "0.6.3"
libsl = { path = ".." }
antlr-rust = { path = "../tool/antlr4-rust-target/runtime/Rust" }
similar = "2.7.0"
yansi = "1.0.1"
